### ISSUE TITLE
Documentation/technical description

### ISSUE THREAD

**Issue by mocquin** [tisimst/soerp#9]
I was wondering if there  was, apart from the docstrings, some documentation or technical explanation about how the package works, from a mathematical point of view ? Or maybe point some wikipedia/online ressource that describes the rational about the foundation of the package

**Comment by IruNikZe** [comment]
@mocquin There is an [R-package](https://www.rdocumentation.org/packages/propagate/versions/1.0-6/topics/propagate) mentioning this package and provides a good summary as well as references.
If some sort of nonlinear error propagation is what you need, I found this to be sufficient in most practical cases since error propagation should not be taken to religiously imo. After all, it's a tool to provide insight in how errors propagate, but deriving super exact numbers from it is both hard and rarely required.

**Comment by mocquin** [comment]
Thanks for pointing the R-package, that should provide enough directions for starters !

**Comment by IruNikZe** [comment]
You're welcome 😃
